# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  erepapidb-benchmarks:
    dependencies:
    - base
    - erepapidb
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: ErepApiDb is a project to make offline eRepublik API for better searching.
executables:
  erepapidb:
    dependencies:
    - base
    - erepapidb
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: brcha/erepapidb
library:
  dependencies:
  - base
  - bytestring
  - cryptonite
  - curl
  - http-api-data
  - time
  - envparse
  source-dirs: library
license: MPL-2.0
license-file: LICENSE.md
maintainer: Filip Brcic
name: erepapidb
synopsis: eRepublik API Database.
tests:
  erepapidb-test-suite:
    dependencies:
    - base
    - erepapidb
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
